trigger:
  branches: { include: [ master ] }
  paths:    { include: [ selenium-soc/** ] }

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenCache: '$(Pipeline.Workspace)/.m2'
  socPom: '$(Build.SourcesDirectory)/selenium-soc/pom.xml'

steps:
  - checkout: self

  - script: |
      echo "Sources dir: $(Build.SourcesDirectory)"
      ls -la $(Build.SourcesDirectory)
      ls -la $(Build.SourcesDirectory)/selenium-soc || true
      test -f "$(socPom)" && echo "POM found: $(socPom)" || (echo "POM NOT FOUND" && exit 1)
    displayName: "Verify repository layout"

  - task: Cache@2
    displayName: 'Cache Maven repo'
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      path: '$(mavenCache)'
      restoreKeys: |
        maven | "$(Agent.OS)"

  - task: Maven@4
    displayName: 'Maven clean test (selenium-soc)'
    inputs:
      mavenPomFile: '$(socPom)'              # <-- explicit full path
      goals: 'clean test'
      options: >-
        -Denv=local -Dbrowser=chrome -Dheadless=true
        -Dmaven.repo.local=$(mavenCache)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenOptions: '-Xmx1024m'
